security:
  expiration: 1000000
  publicKey: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp84G8LAmDLY38bA61aJk
    piLrm5qZV4UrHR4RkJBmtEIqu8iVfL3sk74aoYCXNDC5mROEHgv1apB+Hy65r3yr
    R5RKYbU5dqJx1LahxUEaqi2SOMiQO5y+K2nVMaG3x3DVBzkyX7+zCN4S4uCdImr3
    fqUNtwbKvKMZAdsyW4YB0wCf6O/50TgD1GTfEEH2SO3+DqUiAFYdXzugWwFn7BwW
    bibO8utzEsWnhUe1CdD3t7zCeSODdk/7rGbXU4nrvcj1uqNuZBaN/RkF5kCTT/CM
    l7jbLQgO/Ijb058+AksRjeQJsdWLeMHHeUKhjkxNWb6pbrJTKfl9AjwPeDW/2hUf
    YwIDAQAB
    -----END PUBLIC KEY-----
  privateKey: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCnzgbwsCYMtjfx
    sDrVomSmIuubmplXhSsdHhGQkGa0Qiq7yJV8veyTvhqhgJc0MLmZE4QeC/VqkH4f
    LrmvfKtHlEphtTl2onHUtqHFQRqqLZI4yJA7nL4radUxobfHcNUHOTJfv7MI3hLi
    4J0iavd+pQ23Bsq8oxkB2zJbhgHTAJ/o7/nROAPUZN8QQfZI7f4OpSIAVh1fO6Bb
    AWfsHBZuJs7y63MSxaeFR7UJ0Pe3vMJ5I4N2T/usZtdTieu9yPW6o25kFo39GQXm
    QJNP8IyXuNstCA78iNvTnz4CSxGN5Amx1Yt4wcd5QqGOTE1ZvqluslMp+X0CPA94
    Nb/aFR9jAgMBAAECggEBAJgYBHBZqFMzQee9TMZf54wx8I1cBgquuBIvM8ptJ7nQ
    kz0bJGspFeofj7G8hNAYLdESQFifjDSnfLk0t7bYb8J0JSsEgG4H9NbRJjVMuidv
    IK55E0oE2tUsmsDejF2n5l4iuIbSkSrDZijfX21XuLXAUnsHG/D4f20QSUdtYe/l
    lAUSFU7+NZFB+nJeTtgqK/MPcBTmcL1jYNT8yb4j2CAhmrSreN09Do95TbFCEBcg
    sTLx6HOK9J+p9RJUYIX1X6t6CuLF51pRjUf/JXJl2ne+woC5oYwpSVmNLuD4qevz
    Bp7cau+OhDifNEK3RTIclYVtTSp9+uVJf3uuByHNjPECgYEA177Zjv62g/3ecx0X
    GDNATG2jhsrikzCaqvkTcheyV7SfPecSw4dD/KVA9vAWUhd2mVhht3vcOLvBXedS
    6IsqtP4/QgzLzMFIYhK++PFA3UsKLS7dgKqQrvj5zHEXNAAv+cMZQkNb869DIAa4
    0iUPT5UWUFixnyHuuTvkon2OE1sCgYEAxx1GP7iB78Ed0opkKxNGC5e+OlsK4oBb
    c2wVtbBcJq7nLGnuOA0mqAHCRhck8sXmC2SEkToG6koFx6I+Wj9sNvMBRL5F432N
    F3CfczSSFzdwWyvg6SbzaA+zWWFrMH2r6hpCR4uPOib6U4Pun33j7S5dVSV8tvv/
    sKx5cPheCpkCgYBRlosP2KONJuSJA+dH75nRTWUaBH/KygazwZ3o960qHdRaxJgD
    +ZNsZ9I5kHHgeZ8QPqw1h1Gw4tAtgt2Hs5li+QNTJyOrOyz0acJuwk2VYltm2uJJ
    VjeA9AcDmYD82VVLTsyukmqjrRPleKVMU1eG8QqPN/t0ApEU2+GK0ZB5IQKBgHI2
    QI1ccGvuAgU6jKqIq60KpXsjreKubcaPQQSu3KzztnarbJGKOZo1KBK8Q91d1s7C
    IaiL+Ft7ikUws0NhDdmXGissWTpcUgoX995FUWcvzar+SEx0ozoVh3LFho6SB4KI
    /Wu8ibN5mC0/iCjENXFfHvowPpFXixr0U9SRIqBBAoGBALJ+nZL/AamUmSKSGR9N
    7PqkCraUWLavb+UgV4ybxKevabWBQZOQ4HmNKIAzkQSLoTt9cfoCgbzL9lrzuT6I
    Wx+I3BaLHBTH7SQXrwhPyRf0Vs5pPYNIe+pHbxvU6UKzFhpos1q3wpZBecRvlcBL
    Yx2rWzXbw4Mlj4BcnVmyhEXn
    -----END PRIVATE KEY-----