version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
  user_service:
    build:
      context: ./UserService
      dockerfile: ./Dockerfile
    image: user_service
    container_name: userService
    ports:
      - "8081:8080"
  discovery_service:
    build:
      context: ./DiscoveryService
      dockerfile: ./Dockerfile
    image: discovery_service
    container_name: discoveryService
    ports:
      - "8082:8080"
  auth_service:
    build:
      context: ./AuthService
      dockerfile: ./Dockerfile
    image: auth_service
    container_name: authService
    ports:
      - "8083:8080"
  api_gateway:
    build:
      context: ./ApiGateway
      dockerfile: ./Dockerfile
    image: api_gateway
    container_name: apiGateway
    ports:
      - "8084:8080"


