eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

spring:
  data:
    mongo:
      database: tokenDb
      host: localhost
      port: 27017

  application:
    name: api-gateway-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: true

server:
  port:
    8080