security:
  expiration: 1000000
  tokenEncryptionSecret: thisisa128bitkey
  publicKey: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAomMR+FddPDrUQzMyLIT7
    N9kXHT4Hq3e+PHi/im0nOACOll3cllENdwHie4D5UlKFnlTTSdnevRtekf6CTN2Q
    Vf4FHHNlafeXVZmQd3gZKYnn7HrCJGGCmwfjOeyIHyg3gKXGbhBpkF0bjkjpL9iq
    PnXdrUrY+/FqW5GldMsGDne6HRX6VUNp1JPuX2NObsXlFEEy1BMaNDojf3PnJjQy
    7sA0khm4ujx0QsFGRaY5y40YlGDj4HIFYtI4UODxfmsSQFeaDkXkWVVJI6AgBw0y
    iorjBEIi8z6hZlp0DdP2C5NGJst998ak47qugG/ZKYlHZFp5kfA7XgPNnp0w+9dK
    rwIDAQAB
    -----END PUBLIC KEY-----
  privateKey: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCiYxH4V108OtRD
    MzIshPs32RcdPgerd748eL+KbSc4AI6WXdyWUQ13AeJ7gPlSUoWeVNNJ2d69G16R
    /oJM3ZBV/gUcc2Vp95dVmZB3eBkpiefsesIkYYKbB+M57IgfKDeApcZuEGmQXRuO
    SOkv2Ko+dd2tStj78WpbkaV0ywYOd7odFfpVQ2nUk+5fY05uxeUUQTLUExo0OiN/
    c+cmNDLuwDSSGbi6PHRCwUZFpjnLjRiUYOPgcgVi0jhQ4PF+axJAV5oOReRZVUkj
    oCAHDTKKiuMEQiLzPqFmWnQN0/YLk0Ymy333xqTjuq6Ab9kpiUdkWnmR8DteA82e
    nTD710qvAgMBAAECggEARE2Di3/D2ces7K8mFY/B01Xe4Q/sTfVJ8Umg12reKjIh
    x6GnXRqunTYPu38eX8ASL+ziCpg3ljdi6emxiP9Q7LqyD6uCJrZb00eKepXrj4tQ
    ICnqaz8QnoEM1JpnDyPtZJFWC4mfvXdMVebZHqT1xtvw6CkpZ5+96tIyVBPpcj/C
    Ilc/SZgGX9B7T88O4NKWaddogKQPqyVZ+OerKe7eFfg57p6P4GdQpHjuFDXpeLa8
    xmJpwOMtboiglAheyl98dwbGjawTxs/S9va+YxXfd6u7uSszl8Lb0KcHk/KJVFzJ
    86YdaezeEz7ZnLCkgvlCiRwMam1R926GH4MOYaN9MQKBgQDXdzV2A8wh9360twr6
    JfbGh6H892Cq54ZFLPvfuAT4QwwoBL4+ldWAW0I05bF9Npep68cW2h4PTDeWGPiq
    U33G82P9S2yLEL7ROFGq8tBrv5GPtFR+tmwASIWZ+tVwSQCvLHy/BHLj7DXA6fP5
    ac2LyNnWgFYJFlBxVSwqAVnukwKBgQDA75n1jb5hemS1tUAQ04DNMWPYkQEcFCLy
    YRbxs/cZfZBG9VPpvfUpP+ki+NXeyeQ847WkNNihLCYccfWpc8nik+2sNdBTvYfo
    p1Rs7UR/fjd1s8C5N4Grw4TMJ0tLPq4rLCiV+gxWmEPk2AvdMHosLbogb6lZS9aG
    Q00gHuUo9QKBgEVO0kKQ/CPc8cP9sSk/9v5reJ7fkBfJe7ZavvZ6whZ9srZYuD13
    gwLT2Bsd25b0bZq5/gOKy+qN0L+Wbr6TNr09Y2eB0Ht3OnogTJzZmFNgftkj354W
    3ezFZzxdpDSHNxIiFEp5it9oBu50Eweikfyp8fB+va4UoHGkPR2R67TDAoGBAI7q
    bV9JqfbHFQbMxjIwmb5lkZKAhxPnjqOAa+CK8MU/D7qgS5JfldUCdI3lSXeIkbrQ
    6mJCix2IeIqll9X34VonPe1Mx47gXGZoXM97SjwuoKJdjqskhLdZU2tuyAVq3tU4
    FrBR0wXqMJC5wMAOAtHq5W7Vh9qPpM8710ut1w5pAoGBALI4LAQZzxJeFl5b3PDv
    STMltiNLcLA4GwAYWns89YhOXzP50Y923GPfKd8mcX18lkPdiRAlZLGq1JHBAZ2u
    PaO4Ook0Z+E/sx72RYaNKpJbQFsvZlc/zwxJ8nX6B4vBdWYlxfj3Cj4Q5PPdA5EN
    Xzc337YqtTwXa1fL/8isaeuJ
    -----END PRIVATE KEY-----