jwt:
  secret: thisisasectret

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

spring:
  application:
    name: auth-service
  data:
    mongo:
      database: mytestdb
      host: localhost
      port: 27017

server:
  port:
    8081
